spring.application.name=HRManagementApp
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
logging.level.org.springframework.ws.config.annotation.DelegatingWsConfiguration=ERROR
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
logging.level.com.example.fyp=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.apache.http=DEBUG
logging.level.org.springframework.web.client.RestTemplate=DEBUG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hr.management4226@gmail.com
spring.mail.password=fbqe dyvb uljn yafa
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true